apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workspace
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/jared-logan-patrick-ct/telefonistka-test
      revision: HEAD
      directories:
      - path: workspace/*
  template:
    metadata:
      name: '{{ index .path.segments 1 }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jared-logan-patrick-ct/telefonistka-test
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        name: 'in-cluster'
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamspace=true
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/jared-logan-patrick-ct/telefonistka-test
      revision: HEAD
      directories:
      - path: clusters/local/rancher-desktop/*
  template:
    metadata:
      name: '{{ index .path.segments 3 }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jared-logan-patrick-ct/telefonistka-test
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        name: 'in-cluster'
        namespace: '{{ index .path.segments 3 }}'
      syncPolicy:
        syncOptions:
          - CreateNamspace=true
          - ServerSideApply=true