name: redis
ignoreDifferences:
  - group: ""
    kind: Service
    jqPathExpressions:
      - '.spec.ports[].nodePort'
  - group: apps
    kind: Deployment
    name: guestbook
    namespace: default
    jsonPointers:
    - /spec/replicas